# -*- coding: utf-8 -*-
"""Jsons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbCh_u0DKV5yYEON5G3-kV8H5Xx1Vlg-
"""

from transformers import AutoTokenizer, AutoModel#Trabalha com a utilização de modelos próprios para a situação, não somente o Bert
import torch

tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")#variação do bert proprio para análise de sentenças
model = AutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")

def get_embedding(text):
    tokens = tokenizer(text, return_tensors="pt", padding=True, truncation=True)#Um dicionário cotendo input ids e attention mask
    with torch.no_grad():
        outputs = model(**tokens)#Descompacta o dicionário e passa tokens como argumentos
    return torch.mean(outputs.last_hidden_state, dim=1).squeeze()

import torch.nn.functional as F#Exporta uma série de funções, inlusive a de similaridade por cosseno

meus_assuntos = ["Lei/alteração/educação", "lei/alteração/regularização fundiária", "lei/alteração/reorganização", "lei/premiação/educação", "lei/alteração/cessão"]
assuntos_estado = ["Portaria","Aviso de Licitação","Licença Prévia","Mensagem","Lei Complementar"]
resultados = []
for meu, oficial in zip(meus_assuntos, assuntos_estado):
    emb1 = get_embedding(meu)
    emb2 = get_embedding(oficial)
    similaridade = F.cosine_similarity(emb1, emb2, dim=0)
    resultados.append((meu, oficial, similaridade))

for r in resultados:
    print(f"Meu assunto: {r[0]}\nOficial: {r[1]}\nSimilaridade: {r[2]:.4f}\n")
#Falar pro vinicius que o json ta repetindo publição